# Checkov Security Scanning Configuration
# https://www.checkov.io/2.Basics/Configuration%20File.html

# Framework scanning
framework:
  - terraform
  - github_actions
  - secrets

# Output settings
output:
  - cli
  - sarif

# Severity settings
soft-fail: true
quiet: false
compact: true

# Skip specific checks that are not applicable or too noisy
skip-check:
  # Skip checks that are not relevant for Scaleway
  - CKV_AWS_*
  - CKV_AZURE_*
  - CKV_GCP_*

  # Skip specific Terraform checks that might be too restrictive
  - CKV_TF_1  # Ensure Terraform module sources use a commit hash
  - CKV_TF_2  # Ensure Terraform module sources use a tag with a version number

  # Skip GitHub Actions checks that are too restrictive for our use case
  - CKV_GHA_1  # Ensure no secrets in GitHub Actions
  - CKV_GHA_2  # Ensure GitHub Actions secrets are not hardcoded

  # Skip Docker checks if not using containers in templates
  - CKV_DOCKER_*

# Enable specific checks for enhanced security
check:
  - CKV_TF_*     # All Terraform checks
  - CKV_GHA_*    # All GitHub Actions checks
  - CKV_SECRET_* # All secret detection checks

# External modules and plugins
download-external-modules: true
external-modules-download-path: .external_modules

# Logging
log-level: INFO

# Custom policies directory (if we add custom checks)
external-checks-dir:
  - .checkov/custom_checks

# Baseline file to ignore existing findings (can be created with --create-baseline)
# baseline: .checkov.baseline

# File inclusion/exclusion patterns
skip-path:
  - .terraform/
  - .git/
  - node_modules/
  - __pycache__/
  - .pytest_cache/
  - .coverage/
  - venv/
  - .venv/
  - .external_modules/

# Include specific file patterns
include:
  - "*.tf"
  - "*.tfvars"
  - "*.yml"
  - "*.yaml"
  - "*.json"

# Custom severity mapping for specific checks
custom-policy-output-file: .checkov/custom_policies.json

# Integration settings
create-baseline: false
use-enforcement-rules: false

# Performance settings
parallel: true
enable-secret-scan-all-files: true

# SARIF output configuration
sarif-file-output: true

# Repository settings
repo-root-for-plan-enrichment: .

# Annotations
enable-github-annotations: true

# Policy metadata
policy-metadata-filter:
  - severity:HIGH
  - severity:CRITICAL
  - severity:MEDIUM

# Output format specific settings
output-format-specific:
  sarif:
    include-severity: true
    include-policy-url: true
  cli:
    color: true
    verbose: false